package koinot.com.bot.entity.enums;

public enum UserState {
    CHOOSE_LANGUAGE,
    GET_PHONE_NUMBER,
    EDIT_PHONE_NUMBER,
    SEND_LOCATION,
    EDIT_SEND_LOCATION,
    SEND_ADDRESS,
    EDIT_SEND_ADDRESS,
    SEND_NAME,
    EDIT_SEND_NAME,
    OPEN_TIME_STADIUM,
    EDIT_OPEN_TIME_STADIUM,
    CLOSE_TIME_STADIUM,
    EDIT_CLOSE_TIME_STADIUM,
    GET_PHOTO_STADIUM,
    EDIT_GET_PHOTO_STADIUM,
    GET_PRICE_DAYLIGHT_STADIUM,
    EDIT_GET_PRICE_DAYLIGHT_STADIUM,
    GET_PRICE_NIGHT_STADIUM,
    EDIT_GET_PRICE_NIGHT_STADIUM,
    GET_NIGHT_TIME_FOR_CHANGE_PRICE,
    EDIT_GET_NIGHT_TIME_FOR_CHANGE_PRICE,
    GET_STADIUM_SIZE,
    VERIFY_STADIUM,
    EDIT,
    DEFAULT,

    ///////

    CLIENT_SEND_LOCATION,
    CLIENT_SEND_PHONE_NUMBER
}
